/cm/local/apps/slurm/var/spool/job417884/slurm_script: line 19: /common/ketrong/minconda3/etc/profile.d/conda.sh: No such file or directory
/cm/local/apps/slurm/var/spool/job417884/slurm_script: line 22: $'\nconda create --name tpot2devenv -c conda-forge python=3.10\n': command not found
/cm/local/apps/slurm/var/spool/job417884/slurm_script: line 27: $'\npip install -r requirements.txt\n': command not found
RunStart
2023-11-28 16:29:14.472601: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-28 16:29:14.508160: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-28 16:29:14.508185: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-28 16:29:14.509125: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-28 16:29:14.514473: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-28 16:29:15.736765: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING:tensorflow:From /home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/tensorflow/python/compat/v2_compat.py:108: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
start
working on 
tpot2_imputetest/Impute_Experiments/logs//small_run
loading data
tpot2_imputetest/Impute_Experiments/data/26_True.pkl
starting impute modules
running experiment 1/3 - Does large hyperparameter space improve reconstruction accuracy over simple
[I 2023-11-28 16:29:31,049] A new study created in memory with name: no-name-d8a6c424-100e-499c-9c95-b9e342f8c091
2023-11-28 16:29:32.433763: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:274] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2023-11-28 16:29:32.624170: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:388] MLIR V1 optimization pass is not enabled
[W 2023-11-28 16:29:45,070] Trial 6 failed with parameters: {'model_name': 'GAIN', 'batch_size': 174, 'hint_rate': 0.85, 'alpha': 8, 'iterations': 2} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:45,078] Trial 6 failed with value None.
[W 2023-11-28 16:29:45,493] Trial 8 failed with parameters: {'model_name': 'GAIN', 'batch_size': 196, 'hint_rate': 0.29000000000000004, 'alpha': 48, 'iterations': 1} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:45,496] Trial 8 failed with value None.
[W 2023-11-28 16:29:45,774] Trial 22 failed with parameters: {'model_name': 'GAIN', 'batch_size': 8, 'hint_rate': 0.18000000000000002, 'alpha': 90, 'iterations': 1} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:45,788] Trial 22 failed with value None.
[W 2023-11-28 16:29:46,049] Trial 4 failed with parameters: {'model_name': 'GAIN', 'batch_size': 26, 'hint_rate': 0.77, 'alpha': 14, 'iterations': 17} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:46,049] Trial 4 failed with value None.
[W 2023-11-28 16:29:46,452] Trial 16 failed with parameters: {'model_name': 'GAIN', 'batch_size': 432, 'hint_rate': 0.77, 'alpha': 80, 'iterations': 1} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:46,453] Trial 16 failed with value None.
[W 2023-11-28 16:29:46,726] Trial 27 failed with parameters: {'model_name': 'GAIN', 'batch_size': 2, 'hint_rate': 0.8300000000000001, 'alpha': 17, 'iterations': 1} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:46,731] Trial 27 failed with value None.
[W 2023-11-28 16:29:47,193] Trial 35 failed with parameters: {'model_name': 'GAIN', 'batch_size': 2, 'hint_rate': 0.56, 'alpha': 21, 'iterations': 1} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:47,194] Trial 35 failed with value None.
[W 2023-11-28 16:29:47,484] Trial 7 failed with parameters: {'model_name': 'GAIN', 'batch_size': 1, 'hint_rate': 0.23, 'alpha': 89, 'iterations': 14} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:47,494] Trial 7 failed with value None.
[W 2023-11-28 16:29:47,855] Trial 38 failed with parameters: {'model_name': 'GAIN', 'batch_size': 20, 'hint_rate': 0.7100000000000001, 'alpha': 46, 'iterations': 1} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:47,855] Trial 38 failed with value None.
[W 2023-11-28 16:29:48,123] Trial 10 failed with parameters: {'model_name': 'GAIN', 'batch_size': 310, 'hint_rate': 0.65, 'alpha': 36, 'iterations': 3} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:48,123] Trial 10 failed with value None.
[W 2023-11-28 16:29:48,347] Trial 20 failed with parameters: {'model_name': 'GAIN', 'batch_size': 67, 'hint_rate': 0.22, 'alpha': 21, 'iterations': 1} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:48,347] Trial 20 failed with value None.
[W 2023-11-28 16:29:48,555] Trial 14 failed with parameters: {'model_name': 'GAIN', 'batch_size': 353, 'hint_rate': 0.49, 'alpha': 12, 'iterations': 1} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:48,559] Trial 14 failed with value None.
[W 2023-11-28 16:29:48,878] Trial 21 failed with parameters: {'model_name': 'GAIN', 'batch_size': 116, 'hint_rate': 0.8400000000000001, 'alpha': 70, 'iterations': 2} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:48,879] Trial 21 failed with value None.
[W 2023-11-28 16:29:49,134] Trial 40 failed with parameters: {'model_name': 'GAIN', 'batch_size': 148, 'hint_rate': 0.65, 'alpha': 47, 'iterations': 1} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:49,134] Trial 40 failed with value None.
[W 2023-11-28 16:29:49,544] Trial 31 failed with parameters: {'model_name': 'GAIN', 'batch_size': 496, 'hint_rate': 0.09, 'alpha': 0, 'iterations': 5} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:49,545] Trial 42 failed with parameters: {'model_name': 'GAIN', 'batch_size': 487, 'hint_rate': 0.37, 'alpha': 77, 'iterations': 3} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:49,552] Trial 42 failed with value None.
[W 2023-11-28 16:29:49,545] Trial 31 failed with value None.
[W 2023-11-28 16:29:49,762] Trial 46 failed with parameters: {'model_name': 'GAIN', 'batch_size': 50, 'hint_rate': 0.09, 'alpha': 51, 'iterations': 3} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:50,093] Trial 46 failed with value None.
[W 2023-11-28 16:29:50,485] Trial 3 failed with parameters: {'model_name': 'GAIN', 'batch_size': 64, 'hint_rate': 0.16, 'alpha': 71, 'iterations': 20} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:50,488] Trial 3 failed with value None.
[W 2023-11-28 16:29:50,740] Trial 17 failed with parameters: {'model_name': 'GAIN', 'batch_size': 248, 'hint_rate': 0.8400000000000001, 'alpha': 89, 'iterations': 8} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:50,741] Trial 17 failed with value None.
[W 2023-11-28 16:29:51,078] Trial 34 failed with parameters: {'model_name': 'GAIN', 'batch_size': 1, 'hint_rate': 0.8200000000000001, 'alpha': 6, 'iterations': 7} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:51,078] Trial 34 failed with value None.
[W 2023-11-28 16:29:51,420] Trial 47 failed with parameters: {'model_name': 'GAIN', 'batch_size': 103, 'hint_rate': 0.65, 'alpha': 5, 'iterations': 9} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:51,420] Trial 47 failed with value None.
[W 2023-11-28 16:29:51,950] Trial 30 failed with parameters: {'model_name': 'GAIN', 'batch_size': 4, 'hint_rate': 0.13, 'alpha': 14, 'iterations': 18} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:51,951] Trial 30 failed with value None.
[W 2023-11-28 16:29:52,187] Trial 33 failed with parameters: {'model_name': 'GAIN', 'batch_size': 6, 'hint_rate': 0.37, 'alpha': 66, 'iterations': 13} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:52,188] Trial 33 failed with value None.
[W 2023-11-28 16:29:52,617] Trial 44 failed with parameters: {'model_name': 'GAIN', 'batch_size': 1, 'hint_rate': 0.03, 'alpha': 38, 'iterations': 16} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:52,621] Trial 44 failed with value None.
[W 2023-11-28 16:29:53,053] Trial 29 failed with parameters: {'model_name': 'GAIN', 'batch_size': 122, 'hint_rate': 0.12, 'alpha': 60, 'iterations': 19} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:53,053] Trial 29 failed with value None.
[W 2023-11-28 16:29:53,349] Trial 39 failed with parameters: {'model_name': 'GAIN', 'batch_size': 4, 'hint_rate': 0.38, 'alpha': 17, 'iterations': 25} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:53,350] Trial 39 failed with value None.
[W 2023-11-28 16:29:53,782] Trial 45 failed with parameters: {'model_name': 'GAIN', 'batch_size': 2, 'hint_rate': 0.38, 'alpha': 50, 'iterations': 34} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:53,783] Trial 45 failed with value None.
[W 2023-11-28 16:29:55,411] Trial 25 failed with parameters: {'model_name': 'GAIN', 'batch_size': 12, 'hint_rate': 0.47000000000000003, 'alpha': 23, 'iterations': 64} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:55,412] Trial 25 failed with value None.
[W 2023-11-28 16:29:59,798] Trial 19 failed with parameters: {'model_name': 'GAIN', 'batch_size': 4, 'hint_rate': 0.32, 'alpha': 81, 'iterations': 186} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:29:59,798] Trial 19 failed with value None.
[W 2023-11-28 16:30:00,129] Trial 5 failed with parameters: {'model_name': 'GAIN', 'batch_size': 1, 'hint_rate': 0.16, 'alpha': 62, 'iterations': 210} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:30:00,130] Trial 5 failed with value None.
[W 2023-11-28 16:30:01,826] Trial 9 failed with parameters: {'model_name': 'GAIN', 'batch_size': 14, 'hint_rate': 0.08, 'alpha': 44, 'iterations': 224} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:30:01,826] Trial 9 failed with value None.
[W 2023-11-28 16:30:18,578] Trial 2 failed with parameters: {'model_name': 'GAIN', 'batch_size': 1, 'hint_rate': 0.7000000000000001, 'alpha': 37, 'iterations': 867} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:30:18,583] Trial 2 failed with value None.
[W 2023-11-28 16:30:19,039] Trial 36 failed with parameters: {'model_name': 'GAIN', 'batch_size': 1, 'hint_rate': 0.24000000000000002, 'alpha': 88, 'iterations': 816} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:30:19,039] Trial 36 failed with value None.
[W 2023-11-28 16:30:25,390] Trial 15 failed with parameters: {'model_name': 'GAIN', 'batch_size': 266, 'hint_rate': 0.08, 'alpha': 77, 'iterations': 822} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:30:25,390] Trial 15 failed with value None.
[W 2023-11-28 16:30:57,751] Trial 32 failed with parameters: {'model_name': 'GAIN', 'batch_size': 11, 'hint_rate': 0.5800000000000001, 'alpha': 35, 'iterations': 2334} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:30:57,755] Trial 32 failed with value None.
[W 2023-11-28 16:31:12,128] Trial 11 failed with parameters: {'model_name': 'GAIN', 'batch_size': 68, 'hint_rate': 0.79, 'alpha': 41, 'iterations': 2803} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:31:12,128] Trial 11 failed with value None.
[W 2023-11-28 16:31:32,648] Trial 13 failed with parameters: {'model_name': 'GAIN', 'batch_size': 587, 'hint_rate': 0.43, 'alpha': 92, 'iterations': 2637} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:31:32,654] Trial 13 failed with value None.
[W 2023-11-28 16:31:55,298] Trial 24 failed with parameters: {'model_name': 'GAIN', 'batch_size': 5, 'hint_rate': 0.46, 'alpha': 29, 'iterations': 5239} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:31:55,298] Trial 24 failed with value None.
[W 2023-11-28 16:32:02,049] Trial 23 failed with parameters: {'model_name': 'GAIN', 'batch_size': 32, 'hint_rate': 0.15000000000000002, 'alpha': 66, 'iterations': 5329} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:32:02,052] Trial 23 failed with value None.
[W 2023-11-28 16:32:25,348] Trial 1 failed with parameters: {'model_name': 'GAIN', 'batch_size': 11, 'hint_rate': 0.49, 'alpha': 37, 'iterations': 7066} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:32:25,349] Trial 1 failed with value None.
[W 2023-11-28 16:32:34,785] Trial 43 failed with parameters: {'model_name': 'GAIN', 'batch_size': 93, 'hint_rate': 0.61, 'alpha': 60, 'iterations': 6740} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:32:34,792] Trial 43 failed with value None.
[W 2023-11-28 16:32:42,990] Trial 37 failed with parameters: {'model_name': 'GAIN', 'batch_size': 189, 'hint_rate': 0.9500000000000001, 'alpha': 75, 'iterations': 6809} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:32:42,992] Trial 37 failed with value None.
[W 2023-11-28 16:33:32,379] Trial 18 failed with parameters: {'model_name': 'GAIN', 'batch_size': 58, 'hint_rate': 0.11, 'alpha': 18, 'iterations': 12119} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked_set.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:33:32,394] Trial 18 failed with value None.
[W 2023-11-28 16:34:05,219] Trial 0 failed with parameters: {'model_name': 'GAIN', 'batch_size': 4, 'hint_rate': 0.31, 'alpha': 78, 'iterations': 18985} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked_set.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:34:05,226] Trial 0 failed with value None.
[W 2023-11-28 16:34:07,173] Trial 12 failed with parameters: {'model_name': 'GAIN', 'batch_size': 17, 'hint_rate': 0.49, 'alpha': 92, 'iterations': 18219} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked_set.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:34:07,173] Trial 12 failed with value None.
[W 2023-11-28 16:34:45,480] Trial 41 failed with parameters: {'model_name': 'GAIN', 'batch_size': 613, 'hint_rate': 0.03, 'alpha': 96, 'iterations': 16721} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked_set.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:34:45,482] Trial 41 failed with value None.
[W 2023-11-28 16:37:10,125] Trial 28 failed with parameters: {'model_name': 'GAIN', 'batch_size': 37, 'hint_rate': 0.31, 'alpha': 58, 'iterations': 77764} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked_set.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:37:10,132] Trial 28 failed with value None.
[W 2023-11-28 16:37:32,139] Trial 26 failed with parameters: {'model_name': 'GAIN', 'batch_size': 5, 'hint_rate': 0.6, 'alpha': 3, 'iterations': 91547} because of the following error: NameError("name 'masked' is not defined").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked_set.to_numpy(),1))
NameError: name 'masked' is not defined
[W 2023-11-28 16:37:32,140] Trial 26 failed with value None.
Traceback (most recent call last):
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/small_main.py", line 110, in <module>
    main()
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/small_main.py", line 69, in main
    automodel.fit(X=X_train_missing)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 61, in fit
    self.study.optimize(obj, n_trials=self.n_trials, n_jobs=self.n_jobs, show_progress_bar=self.show_progress, gc_after_trial=self.garbage_collect)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/study.py", line 451, in optimize
    _optimize(
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 103, in _optimize
    f.result()
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 251, in _run_trial
    raise func_err
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 59, in obj
    return autoutils.score(trial, splitting, my_model, X, self.missing_set_train, self.masked_set_train)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoutils.py", line 65, in score
    rmse_val = rmse_loss(ori_data=X.to_numpy(), imputed_data=imputed.to_numpy(), data_m=np.multiply(masked_set.to_numpy(),1))
NameError: name 'masked' is not defined
srun: error: esplhpc-cp002: task 0: Exited with exit code 1
