/cm/local/apps/slurm/var/spool/job417800/slurm_script: line 19: /common/ketrong/minconda3/etc/profile.d/conda.sh: No such file or directory
/cm/local/apps/slurm/var/spool/job417800/slurm_script: line 22: $'\nconda create --name tpot2devenv -c conda-forge python=3.10\n': command not found
/cm/local/apps/slurm/var/spool/job417800/slurm_script: line 27: $'\npip install -r requirements.txt\n': command not found
RunStart
2023-11-28 15:52:41.117790: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-28 15:52:41.153378: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-28 15:52:41.153402: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-28 15:52:41.154757: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-28 15:52:41.160739: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-28 15:52:42.042209: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING:tensorflow:From /home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/tensorflow/python/compat/v2_compat.py:108: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
start
working on 
tpot2_imputetest/Impute_Experiments/logs//small_run
loading data
tpot2_imputetest/Impute_Experiments/data/26_True.pkl
starting impute modules
running experiment 1/3 - Does large hyperparameter space improve reconstruction accuracy over simple
[I 2023-11-28 15:53:00,382] A new study created in memory with name: no-name-5a923134-f793-436a-8050-c24c8c7dcb22
[W 2023-11-28 15:53:00,384] Trial 0 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:00,388] Trial 0 failed with value None.
[W 2023-11-28 15:53:00,385] Trial 1 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:00,603] Trial 1 failed with value None.
[W 2023-11-28 15:53:00,387] Trial 4 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:00,755] Trial 4 failed with value None.
[W 2023-11-28 15:53:00,385] Trial 2 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:00,906] Trial 2 failed with value None.
[W 2023-11-28 15:53:00,388] Trial 3 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:01,057] Trial 3 failed with value None.
[W 2023-11-28 15:53:00,755] Trial 7 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:01,206] Trial 7 failed with value None.
[W 2023-11-28 15:53:00,905] Trial 8 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:01,357] Trial 8 failed with value None.
[W 2023-11-28 15:53:01,206] Trial 9 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:01,507] Trial 9 failed with value None.
[W 2023-11-28 15:53:00,754] Trial 6 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:01,656] Trial 6 failed with value None.
[W 2023-11-28 15:53:01,505] Trial 11 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:01,807] Trial 11 failed with value None.
[W 2023-11-28 15:53:01,356] Trial 10 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:01,955] Trial 10 failed with value None.
[W 2023-11-28 15:53:00,603] Trial 5 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:02,106] Trial 5 failed with value None.
[W 2023-11-28 15:53:01,806] Trial 14 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:02,253] Trial 14 failed with value None.
[W 2023-11-28 15:53:01,955] Trial 15 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:02,404] Trial 15 failed with value None.
[W 2023-11-28 15:53:02,106] Trial 16 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:02,555] Trial 16 failed with value None.
[W 2023-11-28 15:53:01,506] Trial 12 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:02,703] Trial 12 failed with value None.
[W 2023-11-28 15:53:02,106] Trial 17 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:02,857] Trial 17 failed with value None.
[W 2023-11-28 15:53:01,806] Trial 13 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:03,008] Trial 13 failed with value None.
[W 2023-11-28 15:53:02,554] Trial 18 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:03,157] Trial 18 failed with value None.
[W 2023-11-28 15:53:02,855] Trial 22 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:03,308] Trial 22 failed with value None.
[W 2023-11-28 15:53:02,855] Trial 23 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:03,457] Trial 23 failed with value None.
[W 2023-11-28 15:53:02,856] Trial 25 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:03,604] Trial 25 failed with value None.
[W 2023-11-28 15:53:02,857] Trial 27 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:03,754] Trial 27 failed with value None.
[W 2023-11-28 15:53:03,006] Trial 28 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:03,903] Trial 28 failed with value None.
[W 2023-11-28 15:53:03,007] Trial 30 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:04,054] Trial 30 failed with value None.
[W 2023-11-28 15:53:02,853] Trial 20 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:04,206] Trial 20 failed with value None.
[W 2023-11-28 15:53:02,854] Trial 21 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:04,355] Trial 21 failed with value None.
[W 2023-11-28 15:53:03,307] Trial 34 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:04,502] Trial 34 failed with value None.
[W 2023-11-28 15:53:02,857] Trial 26 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:04,654] Trial 26 failed with value None.
[W 2023-11-28 15:53:03,007] Trial 29 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:04,808] Trial 29 failed with value None.
[W 2023-11-28 15:53:03,157] Trial 32 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:04,956] Trial 32 failed with value None.
[W 2023-11-28 15:53:02,856] Trial 24 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:05,105] Trial 24 failed with value None.
[W 2023-11-28 15:53:04,650] Trial 35 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:05,255] Trial 35 failed with value None.
[W 2023-11-28 15:53:04,651] Trial 37 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:05,404] Trial 37 failed with value None.
[W 2023-11-28 15:53:04,653] Trial 39 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:05,551] Trial 39 failed with value None.
[W 2023-11-28 15:53:04,654] Trial 41 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:05,700] Trial 41 failed with value None.
[W 2023-11-28 15:53:04,807] Trial 42 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:05,848] Trial 42 failed with value None.
[W 2023-11-28 15:53:03,307] Trial 33 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:05,999] Trial 33 failed with value None.
[W 2023-11-28 15:53:05,104] Trial 44 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:06,149] Trial 44 failed with value None.
[W 2023-11-28 15:53:04,652] Trial 38 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:06,297] Trial 38 failed with value None.
[W 2023-11-28 15:53:03,008] Trial 31 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:06,445] Trial 31 failed with value None.
[W 2023-11-28 15:53:04,808] Trial 43 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:06,594] Trial 43 failed with value None.
[W 2023-11-28 15:53:05,999] Trial 46 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:06,745] Trial 46 failed with value None.
[W 2023-11-28 15:53:06,148] Trial 47 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:06,897] Trial 47 failed with value None.
[W 2023-11-28 15:53:05,699] Trial 45 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:07,048] Trial 45 failed with value None.
[W 2023-11-28 15:53:04,651] Trial 36 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:07,197] Trial 36 failed with value None.
[W 2023-11-28 15:53:02,703] Trial 19 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:07,344] Trial 19 failed with value None.
[W 2023-11-28 15:53:04,654] Trial 40 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:07,494] Trial 40 failed with value None.
Traceback (most recent call last):
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/small_main.py", line 107, in <module>
    main()
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/small_main.py", line 69, in main
    automodel.fit(X=X_train_missing)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 61, in fit
    self.study.optimize(obj, n_trials=self.n_trials, n_jobs=self.n_jobs, show_progress_bar=self.show_progress, gc_after_trial=self.garbage_collect)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/study.py", line 451, in optimize
    _optimize(
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 103, in _optimize
    f.result()
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 251, in _run_trial
    raise func_err
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
srun: error: esplhpc-cp003: task 0: Exited with exit code 1
