/cm/local/apps/slurm/var/spool/job417799/slurm_script: line 19: /common/ketrong/minconda3/etc/profile.d/conda.sh: No such file or directory
/cm/local/apps/slurm/var/spool/job417799/slurm_script: line 22: $'\nconda create --name tpot2devenv -c conda-forge python=3.10\n': command not found
/cm/local/apps/slurm/var/spool/job417799/slurm_script: line 27: $'\npip install -r requirements.txt\n': command not found
RunStart
2023-11-28 15:52:42.155149: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-28 15:52:42.188963: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-28 15:52:42.188985: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-28 15:52:42.189888: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-28 15:52:42.195146: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-28 15:52:43.520078: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING:tensorflow:From /home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/tensorflow/python/compat/v2_compat.py:108: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
start
working on 
tpot2_imputetest/Impute_Experiments/logs//small_run
loading data
tpot2_imputetest/Impute_Experiments/data/26_True.pkl
starting impute modules
running experiment 1/3 - Does large hyperparameter space improve reconstruction accuracy over simple
[I 2023-11-28 15:52:59,067] A new study created in memory with name: no-name-3070ab19-8f07-4ba0-b38d-1655c2a730be
[W 2023-11-28 15:52:59,068] Trial 0 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:52:59,088] Trial 0 failed with value None.
[W 2023-11-28 15:52:59,070] Trial 2 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:52:59,295] Trial 2 failed with value None.
[W 2023-11-28 15:52:59,072] Trial 4 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:52:59,442] Trial 4 failed with value None.
[W 2023-11-28 15:52:59,073] Trial 5 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:52:59,584] Trial 5 failed with value None.
[W 2023-11-28 15:52:59,074] Trial 7 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:52:59,734] Trial 7 failed with value None.
[W 2023-11-28 15:52:59,075] Trial 9 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:52:59,877] Trial 9 failed with value None.
[W 2023-11-28 15:52:59,077] Trial 11 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:00,026] Trial 11 failed with value None.
[W 2023-11-28 15:52:59,078] Trial 14 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:00,173] Trial 14 failed with value None.
[W 2023-11-28 15:52:59,079] Trial 15 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:00,316] Trial 15 failed with value None.
[W 2023-11-28 15:52:59,081] Trial 18 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:00,461] Trial 18 failed with value None.
[W 2023-11-28 15:52:59,082] Trial 19 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:00,603] Trial 19 failed with value None.
[W 2023-11-28 15:52:59,083] Trial 21 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:00,748] Trial 21 failed with value None.
[W 2023-11-28 15:52:59,084] Trial 23 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:00,892] Trial 23 failed with value None.
[W 2023-11-28 15:52:59,086] Trial 25 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:01,035] Trial 25 failed with value None.
[W 2023-11-28 15:52:59,087] Trial 27 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:01,178] Trial 27 failed with value None.
[W 2023-11-28 15:52:59,071] Trial 3 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:01,320] Trial 3 failed with value None.
[W 2023-11-28 15:52:59,297] Trial 29 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:01,463] Trial 29 failed with value None.
[W 2023-11-28 15:52:59,073] Trial 6 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:01,606] Trial 6 failed with value None.
[W 2023-11-28 15:52:59,730] Trial 31 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:01,750] Trial 31 failed with value None.
[W 2023-11-28 15:52:59,876] Trial 33 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:01,892] Trial 33 failed with value None.
[W 2023-11-28 15:52:59,077] Trial 12 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:02,035] Trial 12 failed with value None.
[W 2023-11-28 15:53:00,024] Trial 35 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:02,176] Trial 35 failed with value None.
[W 2023-11-28 15:52:59,080] Trial 16 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:02,322] Trial 16 failed with value None.
[W 2023-11-28 15:52:59,080] Trial 17 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:02,464] Trial 17 failed with value None.
[W 2023-11-28 15:52:59,082] Trial 20 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:02,607] Trial 20 failed with value None.
[W 2023-11-28 15:52:59,084] Trial 22 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:02,749] Trial 22 failed with value None.
[W 2023-11-28 15:52:59,085] Trial 24 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:02,892] Trial 24 failed with value None.
[W 2023-11-28 15:53:01,035] Trial 40 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:03,037] Trial 40 failed with value None.
[W 2023-11-28 15:53:01,178] Trial 41 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:03,181] Trial 41 failed with value None.
[W 2023-11-28 15:52:59,442] Trial 30 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:03,324] Trial 30 failed with value None.
[W 2023-11-28 15:52:59,074] Trial 8 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:03,468] Trial 8 failed with value None.
[W 2023-11-28 15:52:59,076] Trial 10 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:03,612] Trial 10 failed with value None.
[W 2023-11-28 15:53:00,025] Trial 36 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:03,755] Trial 36 failed with value None.
[W 2023-11-28 15:52:59,078] Trial 13 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:03,898] Trial 13 failed with value None.
[W 2023-11-28 15:53:00,460] Trial 38 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:04,039] Trial 38 failed with value None.
[W 2023-11-28 15:53:02,607] Trial 45 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:04,183] Trial 45 failed with value None.
[W 2023-11-28 15:53:02,749] Trial 46 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:04,325] Trial 46 failed with value None.
[W 2023-11-28 15:52:59,069] Trial 1 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:04,467] Trial 1 failed with value None.
[W 2023-11-28 15:53:01,462] Trial 42 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:04,610] Trial 42 failed with value None.
[W 2023-11-28 15:52:59,733] Trial 32 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:04,751] Trial 32 failed with value None.
[W 2023-11-28 15:53:00,023] Trial 34 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:04,894] Trial 34 failed with value None.
[W 2023-11-28 15:53:00,459] Trial 37 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:05,036] Trial 37 failed with value None.
[W 2023-11-28 15:52:59,086] Trial 26 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:05,178] Trial 26 failed with value None.
[W 2023-11-28 15:53:03,323] Trial 47 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:05,320] Trial 47 failed with value None.
[W 2023-11-28 15:53:02,322] Trial 44 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:05,474] Trial 44 failed with value None.
[W 2023-11-28 15:52:59,296] Trial 28 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:05,624] Trial 28 failed with value None.
[W 2023-11-28 15:53:01,892] Trial 43 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:05,767] Trial 43 failed with value None.
[W 2023-11-28 15:53:00,603] Trial 39 failed with parameters: {} because of the following error: AttributeError("'numpy.ndarray' object has no attribute 'columns'").
Traceback (most recent call last):
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
[W 2023-11-28 15:53:05,908] Trial 39 failed with value None.
Traceback (most recent call last):
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/small_main.py", line 107, in <module>
    main()
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/small_main.py", line 69, in main
    automodel.fit(X=X_train_missing)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 61, in fit
    self.study.optimize(obj, n_trials=self.n_trials, n_jobs=self.n_jobs, show_progress_bar=self.show_progress, gc_after_trial=self.garbage_collect)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/study.py", line 451, in optimize
    _optimize(
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 103, in _optimize
    f.result()
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 251, in _run_trial
    raise func_err
  File "/home/ketrong/miniconda3/envs/tpot2devenv/lib/python3.10/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/common/ketrong/AutoImputeExp/tpot2_imputetest/Impute_Experiments/autoimpute.py", line 56, in obj
    my_params = autoutils.trial_suggestion(trial, self.model_names, column_len=len(X.columns), random_state=self.random_state)
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
srun: error: esplhpc-cp002: task 0: Exited with exit code 1
